// js/language.js
// Multilingual dictionary for GradeMaster (ru, kk, en)

const translations = {
    'ru': {
        "add_assignment": "+ Добавить задание",
        "add_exam": "+ Добавить экзамен",
        "add_quiz": "+ Добавить тест",
        "already_failed_1": "По текущим результатам сдать курс невозможно.",
        "already_failed_2": "Даже идеальный файнал не спасёт ситуацию.",
        "assignment": "Задание",
        "assignments": "Задания",
        "att_allowed_miss_text": "Вы можете пропустить <span class=\"highlight\">{missed}</span> пар.",
        "att_allowed_percentage": "Допустимый процент пропусков:",
        "att_calc_completed": "✅ Расчет завершен",
        "att_calc_step1": "1. Всего пар за 10 недель:",
        "att_calc_step2": "2. Допустимый процент пропусков:",
        "att_calc_step3": "3. Расчет:",
        "att_calc_step4": "4. Округление до целого числа:",
        "att_calculation": "Расчёт:",
        "att_description": "Этот калькулятор покажет, сколько занятий можно пропустить за 10 недель семестра.",
        "att_done": "✅ Расчёт завершён",
        "att_error": "Ошибка",
        "att_how": "Как это рассчитывается:",
        "att_how_calculated": "Как это рассчитывается:",
        "att_lessons_label": "Количество занятий в неделю (одно занятие — 50 минут):",
        "att_lessons_placeholder": "Введите число от 1 до 20",
        "att_missed": "Можно пропустить занятий: {count}.",
        "att_note": "Фактическое количество допустимых пропусков может зависеть от конкретного предмета, сверьтесь с силлабусом данного курса.",
        "att_note_prefix": "Примечание:",
        "att_percentage": "Допустимый процент пропусков:",
        "att_placeholder": "Введите целое число от 1 до 20",
        "att_please_enter": "Пожалуйста, введите количество пар в неделю.",
        "att_range_error": "Количество пар должно быть от 1 до 20.",
        "att_rounding": "Округление вниз до целого:",
        "att_summary": "За 10 недель при {weekly} занятиях в неделю:",
        "att_summary_text": "За 10 недель семестра при <span class=\"highlight\">{lessons}</span> парах в неделю:",
        "att_total": "Всего занятий за 10 недель:",
        "bank_details": "Реквизиты:",
        "bank_title": "💳 Банковский перевод",
        "calculate_btn": "Рассчитать",
        "calculate_cumulative": "Рассчитать средний GPA",
        "calculate_gpa": "Рассчитать GPA",
        "calculate_gpa_btn": "Рассчитать GPA",
        "calculate_total": "Рассчитать итоговую оценку",
        "calculator_title": "📚 Калькулятор оценок",
        "component": "Работа",
        "convert_btn": "Конвертировать в GPA",
        "converter_button": "Конвертер оценок",
        "converter_description": "Перевод процентной оценки в GPA",
        "converter_title": "🔄 Конвертер оценок в GPA",
        "copy_btn": "Копировать",
        "copy_button": "Копировать",
        "copy_error": "Не удалось скопировать. Скопируйте ссылку вручную.",
        "critical_check": "Проверка критических условий",
        "cumulative_count_error": "Введите целое количество триместров от 1 до 20.",
        "cumulative_credits": "Кредиты",
        "cumulative_data_error": "GPA должен быть от 0 до 4, кредиты — больше 0.",
        "cumulative_desc": "Введите GPA и кредиты для каждого триместра",
        "cumulative_error_count": "❌ Пожалуйста, введите корректное количество триместров (1-20)",
        "cumulative_error_insufficient": "❌ Недостаточно данных для расчета.",
        "cumulative_error_validate": "❌ Пожалуйста, проверьте введенные данные. GPA должен быть от 0 до 4, кредиты больше 0.",
        "cumulative_gpa": "GPA",
        "cumulative_results": "📋 Результаты расчета",
        "cumulative_term": "Триместр",
        "cumulative_title": "📈 Калькулятор среднего GPA",
        "cumulative_total": "Общий GPA (средневзвешенный):",
        "cumulative_warning": "⚠️ Введите корректные данные для всех триместров!",
        "cumulative_weighted": "GPA × Кредиты",
        "current_mode": "Текущий режим:",
        "custom_amount": "Другая сумма",
        "danger_fail": "❌ Летник",
        "description": "Набор инструментов для студентов",
        "details_calculation": "Детали расчёта: РегТерм = {regterm}, Итоговый балл = {total}",
        "details_calculation_evil": "Детали: РегТерм = {regterm}, Итоговый = {total}",
        "details_calculation_standard": "РегТерм: {regterm}{source} | Итого: {total}",
        "empty_msg_1": "Пожалуйста, введите все значения для расчёта.",
        "empty_msg_2": "Все поля должны быть заполнены для точного результата.",
        "endterm": "Эндтерм",
        "error_empty": "❌ Пожалуйста, введите все значения для расчёта.",
        "error_invalid": "❌ Ошибка: Все оценки должны быть в диапазоне от 0 до 100",
        "evil_advice_lucky": "💡 Совет: В этот раз повезло >:)",
        "evil_advice_memes": "💡 Совет: Может, стоило больше учиться, а не листать мемы?",
        "evil_already_failed_1": "По текущим результатам дела обстоят плохо.",
        "evil_already_failed_2": "Даже 100 на файнале не спасёт. Летник неизбежен.",
        "evil_empty_1": "Ты серьёзно забыл ввести числа? Или это тоже нужно объяснять?",
        "evil_empty_2": "Ничего не введено. Серьёзно?",
        "evil_fail_1": "Летник. Не плачь, я просто посчитал. Встретимся на пересдаче!",
        "evil_fail_2": "Ты провалился. На счастье это было предсказуемо.",
        "evil_high_1": "Потрясающий результат! Оказывается, ты тоже можешь что-то.",
        "evil_high_2": "Ну, впечатлён! Продолжай так.",
        "evil_high_scholarship_1": "Серьёзно? Повышенная стипендия? Ты точно не списывал?",
        "evil_high_scholarship_2": "Не ожидал такого от тебя!",
        "evil_high_scholarship_comment_easy": " (Это реально!)",
        "evil_high_scholarship_comment_fantasy": " (Начинай молиться 🙏)",
        "evil_high_scholarship_comment_hard": " (Выучи ВСЁ!)",
        "evil_impossible_high": "Повышенная стипендия? С такими оценками? Мечтать не вредно! 😂",
        "evil_invalid_1": "Оценки от 0 до 100, а не от минус бесконечности до 200. Математику учили?",
        "evil_invalid_2": "Некорректные данные. Ты точно на этом курсе?",
        "evil_pass_1": "Выжил. Едва, но выжил. Поздравляю с минимальным результатом.",
        "evil_pass_2": "Ну, ты сдал. Почти чудо.",
        "evil_pass_comment_easy": " (Вполне реально)",
        "evil_pass_comment_hard": " (Ого! Это будет СЛОЖНО)",
        "evil_pass_comment_medium": " (Готовься жить в библиотеке)",
        "evil_scholarship_1": "Со стипендией! Не растрать её на кофе в первый же день.",
        "evil_scholarship_2": "Поздравляю, стипендия твоя!",
        "evil_scholarship_comment_fantasy": " (Это уже из области фантастики!)",
        "evil_scholarship_comment_hard": " (На грани возможного!)",
        "evil_scholarship_comment_medium": " (Потребуются невероятные усилия)",
        "evil_tip_lucky": "💡 Совет: В этот раз повезло >:)",
        "evil_tip_study": "💡 Совет: Может, стоило больше учиться, а не листать мемы?",
        "exam": "Экзамен",
        "exams": "Экзамены",
        "expired_link": "❌ Срок действия ссылки истёк",
        "failed_title": "❌ Летник",
        "feature_all_subjects": "• Подходит для любых предметов",
        "feature_clear_method": "• Понятный метод подсчета",
        "feature_cumulative1": "• Учёт разного количества кредитов",
        "feature_cumulative2": "• Поддержка до 20 триместров",
        "feature_cumulative3": "• Точность до двух знаков",
        "feature_fast_start": "• Быстрый старт",
        "feature_manual": "• Ручной ввод всех параметров",
        "feature_popular_subjects": "• Популярные предметы",
        "feature_preset_weights": "• Предустановленные веса",
        "feature_readable_interface": "• Читаемый интерфейс",
        "feature_transparency": "• Максимальная прозрачность",
        "feedback_anonymous": "Анонимный пользователь",
        "feedback_contact": "Контакт (если нужен ответ):",
        "feedback_contact_label": "Контакт (если нужен ответ):",
        "feedback_contact_placeholder": "Telegram, email или др.",
        "feedback_cooldown_notice": "Пожалуйста, подождите. Следующее сообщение можно отправить через {time}.",
        "feedback_cooldown_prefix": "Повторная отправка через",
        "feedback_description": "Есть идеи по улучшению калькулятора или нашли ошибку? Напишите нам — мы ценим ваше мнение!",
        "feedback_draft_restored": "✅ Текст обращения восстановлен в форме!",
        "feedback_error": "Ошибка отправки сообщения",
        "feedback_error_try_again": "❌ Произошла ошибка. Попробуйте еще раз.",
        "feedback_from": "От:",
        "feedback_invalid": "Не удалось обработать сообщение. Обновите страницу и попробуйте ещё раз.",
        "feedback_limits": "До 3000 символов в сообщении, 100 в имени и 200 в контакте.",
        "feedback_message": "Сообщение:*",
        "feedback_message_label": "Сообщение:*",
        "feedback_message_placeholder": "Опишите вашу идею, проблему или предложение...",
        "feedback_name": "Ваше имя (необязательно):",
        "feedback_name_label": "Ваше имя (необязательно):",
        "feedback_name_placeholder": "Как к вам обращаться?",
        "feedback_network_error": "Не удалось связаться с сервером. Проверьте интернет-соединение. Введённый текст остался в форме.",
        "feedback_rate_limited": "Слишком много запросов. Подождите немного перед повторной отправкой.",
        "feedback_required": "Введите сообщение перед отправкой.",
        "feedback_restore_btn": "↩️ Вернуть текст обращения",
        "feedback_sending": "Отправка...",
        "feedback_source": "Источник:",
        "feedback_submit": "📨 Отправить сообщение",
        "feedback_submit_btn": "📨 Отправить сообщение",
        "feedback_subtitle": "Есть идеи по улучшению калькулятора? Нашли ошибку?<br>Напишите нам — мы ценим ваше мнение!",
        "feedback_success": "Спасибо за вашу обратную связь!",
        "feedback_success_contact": "Мы скоро свяжемся с вами!",
        "feedback_time": "Время:",
        "feedback_timeout": "Сервер не успел подтвердить отправку. Сообщение могло быть доставлено. Введённый текст остался в форме.",
        "feedback_too_long": "Сократите текст: до 3000 символов в сообщении, 100 в имени и 200 в контакте.",
        "feedback_type": "Тип обращения:",
        "feedback_type_bug": "🐛 Сообщение об ошибке",
        "feedback_type_feature": "🚀 Запрос новой функции",
        "feedback_type_label": "Тип обращения:",
        "feedback_type_other": "📝 Другое",
        "feedback_type_suggestion": "💡 Предложение по улучшению",
        "feedback_unavailable": "Обратная связь временно недоступна. Попробуйте позже — введённый текст остался в форме.",
        "feedback_user_anonymous": "Анонимный пользователь",
        "final_label": "Файнал (0-100)",
        "final_placeholder": "Оставьте пустым для прогноза",
        "footer_copyright": "&copy; 2025 Not_404. In case of any bug contact via Telegram",
        "for_high_scholarship": "Для повышенной стипендии:",
        "for_high_scholarship_title": "💎 Для повышенной стипендии:",
        "for_pass": "Для прохода курса:",
        "for_pass_title": "📝 Для прохода курса:",
        "for_regular_scholarship": "Для обычной стипендии:",
        "for_scholarship_title": "💰 Для обычной стипендии:",
        "generate_qr": "✨ Создать QR-код",
        "generate_subjects": "Сгенерировать форму для предметов",
        "generate_terms": "Сгенерировать поля",
        "go_button": "Перейти",
        "gpa_button": "Калькулятор GPA",
        "gpa_calc_results_title": "📋 Результаты расчета",
        "gpa_correct_count": "Пожалуйста, введите корректное количество предметов (1-20)",
        "gpa_credits_col": "Кредиты",
        "gpa_credits_placeholder": "Кредиты",
        "gpa_description": "Расчет средневзвешенного GPA с учетом кредитов",
        "gpa_fill_all": "Пожалуйста, проверьте введенные данные. Все поля должны быть заполнены корректно.",
        "gpa_formula": "GPA = Σ(GPA<sub>предмета</sub> × кредиты) / Σ(кредиты)",
        "gpa_gpa_col": "GPA",
        "gpa_grade_col": "Оценка (%)",
        "gpa_grade_placeholder": "Оценка (%)",
        "gpa_insufficient": "Недостаточно данных для расчета. Добавьте хотя бы один предмет с кредитами и оценкой.",
        "gpa_item_prefix": "Предмет",
        "gpa_overall": "Общий GPA (средневзвешенный):",
        "gpa_subject_col": "Предмет",
        "gpa_subject_name": "Название предмета",
        "gpa_title": "📊 GPA Calculator",
        "gpa_warning": "⚠️ Важно: Введите корректные данные для всех предметов!",
        "gpa_weighted_col": "GPA × Кредиты",
        "grade_percentage": "Оценка (%)",
        "grade_range": "Оценка (0–100)",
        "high_comment_easy": " (сложно, но возможно)",
        "high_comment_hard": " (практически нереально)",
        "high_impossible": "Невозможно получить повышенную стипендию при текущих результатах.",
        "high_impossible_evil": "Повышенная стипендия? С такими оценками? Мечтать не вредно! 😂",
        "high_scholarship_title": "💎 Превосходно! Повышенная стипендия!",
        "higher_scholarship": "Повышенная стипендия невозможна",
        "important_info": "ℹ️ Важная информация:",
        "impossible_pass": "Невозможно (нужно {value} > 100)",
        "impossible_scholarship": "Нужно больше 100 баллов. Может, попробуешь взятку? Шучу... или нет 🤔",
        "impossible_scholarship_evil": "Нужно больше 100 баллов. Может, попробуешь взятку? Шучу... или нет 🤔",
        "impossible_scholarship_serious": "Невозможно получить стипендию при текущих результатах.",
        "impossible_scholarship_standard": "Невозможно получить стипендию при текущих результатах.",
        "invalid_link": "❌ Ссылка недействительна или устарела",
        "invalid_msg_1": "Введите корректные значения от 0 до 100.",
        "invalid_msg_2": "Некорректные данные, проверяйте диапазон оценок.",
        "kaspi_card": "Номер карты:",
        "kaspi_title": "🇰🇿 Kaspi перевод",
        "language_label": "Язык",
        "link_copied": "✅ Ссылка скопирована.",
        "main_description": "Выберите тип калькулятора",
        "main_title": "GradeMaster - Главная страница",
        "midterm": "Мидтерм",
        "minimum_points": "Минимум {value} баллов",
        "mode_evil": "Злой старшекурсник",
        "mode_evil_msg": "Режим злого старшекурсника.",
        "mode_serious": "Серьёзный режим",
        "mode_serious_msg": "Режим серьёзного аналитика.",
        "mode_standard": "Стандартный режим",
        "mode_standard_msg": "Стандартный режим. Всё по делу.",
        "nav_evil": "Злой старшекурсник",
        "nav_feedback": "💬 Обратная связь",
        "nav_home": "← Главная",
        "nav_language": "🌐 Қаз",
        "nav_mode": "Сменить режим",
        "nav_serious": "Серьёзный режим",
        "nav_standard": "Стандартный режим",
        "nav_theme": "🌙 Тема",
        "option_att_desc": "Отслеживание и расчет посещаемости",
        "option_att_title": "📋 Калькулятор Посещаемости",
        "option_attendance_desc": "Удобный калькулятор для подсчета своей посещаемости",
        "option_attendance_title": "📚 Калькулятор посещаемости",
        "option_converter_desc": "Перевод процентной оценки в GPA",
        "option_converter_title": "🔄 Конвертер оценок в GPA",
        "option_cumulative_desc": "Рассчитайте общий GPA с учётом кредитов за несколько триместров",
        "option_cumulative_title": "📈 Средний GPA за триместры",
        "option_feedback_desc": "Помогите улучшить приложение",
        "option_feedback_title": "💬 Обратная связь",
        "option_gpa_desc": "Калькулятор помогающий понять сколько вы получили",
        "option_gpa_title": "📊 Калькулятор Итогового GPA",
        "option_templates_desc": "Готовые настройки для популярных направлений",
        "option_templates_title": "📚 Предметные шаблоны",
        "option_total_desc": "Калькулятор помогающий понять как сильно надо готовиться",
        "option_total_title": "🚀 Калькулятор Итоговой Оценки",
        "page_title_attendance": "Attendance Calculator - GradeMaster",
        "page_title_cumulative": "Средний GPA — GradeMaster",
        "page_title_feedback": "GradeMaster - Обратная связь",
        "page_title_gpa": "GPA Calculator - GradeMaster",
        "page_title_template": "Grade Calculator - Структурированный",
        "page_title_total": "GradeMaster - Калькулятор оценок",
        "pass_msg_1": "Вы прошли курс. Итоговая оценка в пределах нормы.",
        "pass_msg_2": "Курс сдан успешно, поздравляем!",
        "pass_title": "⚠️ Без стипендии",
        "percentage_label": "Итоговая оценка в процентах (%):",
        "percentage_placeholder": "Например: 85",
        "prediction_msg_1": "Расчёт необходимых баллов:",
        "prediction_msg_2": "Сколько нужно набрать на файнале:",
        "prediction_title": "🔮 Прогноз",
        "preset_description": "Сохраните веса и список работ в ссылку. Оценки в пресет не попадают.",
        "preset_error": "❌ Не получилось создать ссылку на пресет.",
        "preset_invalid": "❌ Ссылка на пресет повреждена или устарела.",
        "preset_link_label": "Ссылка на пресет",
        "preset_loaded": "📥 Пресет загружен из ссылки.",
        "preset_save": "Сохранить пресет",
        "preset_saved": "✅ Пресет сохранён. Ссылку можно отправить другому человеку.",
        "preset_title": "🔗 Пресет предмета",
        "qr_description": "Отсканируйте QR-код для открытия приложения Kaspi с заполненными реквизитами:",
        "quick_transfer": "📱 Быстрый перевод через Kaspi",
        "quiz": "Тест",
        "quizzes": "Тесты",
        "regend_below_25_evil": "РегЭнд < 25... Кажется, кто-то пропустил пару важных лекций. Или все.",
        "regend_below_25_serious": "РегЭнд ниже минимального порога. Курс не может быть сдан.",
        "regend_below_25_standard": "РегЭнд меньше 25. Летник без вариантов.",
        "regend_label": "РегЭнд (0-100)",
        "regend_placeholder": "Введите оценку",
        "regmid_below_25": "РегМид < 25? Серьёзно? Вы вообще на пары ходили? 💀",
        "regmid_below_25_standard": "РегМид меньше 25. Летник без вариантов.",
        "regmid_below_minimum": "РегМид ниже минимального порога. Курс не может быть сдан.",
        "regmid_label": "РегМид (0-100)",
        "regmid_placeholder": "Введите оценку",
        "regterm_below_50": "РегТерм < 50. Поздравляю, ты даже до файнала не добрался а уже летка!",
        "regterm_below_50_serious": "РегТерм ниже минимального порога. Курс не может быть сдан.",
        "regterm_below_50_standard": "РегТерм меньше 50. Летник неизбежен.",
        "regterm_calculated": " (вычислен из РегМида и РегЭнда)",
        "regterm_direct_input": " (введён напрямую)",
        "regterm_display": "РегТерм: {value}{source}",
        "regterm_label": "РегТерм (0-100)",
        "regterm_placeholder": "Или введите РегТерм напрямую",
        "regterm_source_calc": " (вычислен из РегМида и РегЭнда)",
        "remove_item": "Удалить строку",
        "retake_evil": "Файнал между 25 и 50. Судьба дала второй шанс, не облажайся.",
        "retake_serious": "Экзамен не сдан, но предоставляется возможность пересдачи.",
        "retake_standard": "Пересдача. У вас есть второй шанс.",
        "retake_title": "⚠️ Пересдача",
        "scholarship_title": "✅ Успех! Обычная стипендия!",
        "secret_auto_passing": "Функция 'автоматического прохождения экзамена' еще в разработке...",
        "secret_calculator_scholarship": "Если бы этот калькулятор был студентом, у него была бы стипендия!",
        "secret_calculator_student": "Знаете, почему калькулятор такой точный? Он не списывал на экзаменах!",
        "secret_difference": "Знаете разницу между студентом и этим калькулятором? Калькулятор всегда считает правильно!",
        "secret_easter_egg": "Мои поздравления пасхантер, может и на других страницах что то есть?)",
        "secret_excuse": "Поздравляю! Вы нашли оправдание не готовиться к экзамену!",
        "secret_extra_1": "Пасхалка! Ты нашел секрет! 🥚",
        "secret_extra_10": "Разработчик был здесь 🐛",
        "secret_extra_11": "Это сообщение самоликвидируется через 5... 4... 3... шучу!",
        "secret_extra_12": "Пасхалка уровня 'я должен был учиться, но ищу пасхалки'",
        "secret_extra_13": "Инсайдерская информация: преподы тоже пользуются калькуляторами!",
        "secret_extra_14": "Секретный ингредиент хорошей оценки - уверенность (и этот калькулятор)",
        "secret_extra_15": "Функция 'автопропуск пар' временно отключена... к сожалению",
        "secret_extra_16": "Знаете, что общего у этого калькулятора и хорошей оценки? Оба требуют правильных входных данных!",
        "secret_extra_17": "Внимание! Обнаружена корреляция между использованием калькулятора и снижением уровня паники!",
        "secret_extra_2": "Разработчик этого калькулятора тоже иногда заваливает экзамены 😅",
        "secret_extra_3": "Знаешь ли ты, что первый калькулятор был создан в 17 веке?",
        "secret_extra_4": "Этот калькулятор был сделан с ♥ и большим количеством кофе ☕",
        "secret_extra_5": "Интересный факт: 87% студентов находят пасхалки во время подготовки к экзаменам",
        "secret_extra_6": "Пссс... между нами, РегМид весит 30%, но все делают вид, что это не так",
        "secret_extra_7": "Разработчик рекомендует: одна пасхалка в день - и сессия не страшна!",
        "secret_extra_8": "Факт: 100% пользователей этого калькулятора успешно отвлекаются от учебы!",
        "secret_extra_9": "Секретная формула: сон + еда + этот калькулятор = успешная сессия!",
        "secret_hack": "Хакерский совет: чтобы сдать экзамен, нужно на него прийти 😉",
        "secret_leak": "Внимание! Обнаружена утечка: файнал составляет 40% от оценки!",
        "secret_manual_check": "Секретный совет: всегда проверяйте расчеты вручную!",
        "secret_rare_user": "Ты - 1 из 1000 пользователей, который нашел эту пасхалку!",
        "secret_subtitle": "👀 Ты что, ищешь скрытый смысл? Его нет!",
        "secret_success": "Секрет успеха: 10% везение, 20% навыки, 70% этот калькулятор!",
        "secret_theme": "🎨 Художник? Так быстро переключаешь темы!",
        "secret_triple": "🎉 Тройной клик! Ты явно заскучал на парах!",
        "secret_warning": "Предупреждение: чрезмерное использование калькулятора может привести к... хорошим оценкам!",
        "select_amount": "Выберите сумму (₸):",
        "serious_impossible_high": "Невозможно получить повышенную стипендию при текущих результатах.",
        "serious_pass_comment": "",
        "serious_scholarship_comment_easy": " (высокая сложность)",
        "serious_scholarship_comment_hard": " (экстремально сложно)",
        "serious_scholarship_comment_medium": " (очень высокая сложность)",
        "share_button": "🔗 Создать ссылку для друга",
        "share_copied_success": "✅ Ссылка скопирована в буфер обмена!",
        "share_created": "✅ Ссылка создана! Она будет активна 24 часа.",
        "share_created_success": "✅ Ссылка создана! Данные сохранены в ссылке.",
        "share_data_loaded": "📥 Данные загружены из общей ссылки!",
        "share_info": "Эта ссылка сохраняет все введённые данные для отправки другу",
        "share_link_label": "Ссылка для общего доступа:",
        "share_loaded": "📥 Данные загружены из общей ссылки!",
        "sigma_credits": "Σ(кредиты)",
        "sigma_gpa_credits": "Σ(GPA × кредиты)",
        "standard_empty_1": "Заполните все поля для расчёта.",
        "standard_empty_2": "Не забудьте ввести все оценки.",
        "standard_fail_1": "К сожалению, результат ниже проходного балла.",
        "standard_fail_2": "Летник неизбежен, пора пересдавать.",
        "standard_high_1": "Отличный результат! Вы показали высокий уровень знаний.",
        "standard_high_2": "Превосходно! Так держать.",
        "standard_high_scholarship_1": "Превосходно! Вы получаете повышенную стипендию!",
        "standard_high_scholarship_2": "Высший результат! Повышенная стипендия гарантирована!",
        "standard_high_scholarship_comment_easy": " (сложно, но возможно)",
        "standard_high_scholarship_comment_hard": " (практически нереально)",
        "standard_high_scholarship_comment_medium": " (очень сложно)",
        "standard_invalid_1": "Оценки должны быть от 0 до 100.",
        "standard_invalid_2": "Некорректное значение, проверяйте диапазон.",
        "standard_pass_1": "Вы прошли курс. Итоговая оценка в пределах нормы.",
        "standard_pass_2": "Курс сдан успешно, поздравляем!",
        "standard_pass_comment_easy": " (достижимо)",
        "standard_pass_comment_hard": " (очень сложно)",
        "standard_pass_comment_medium": " (нужна хорошая подготовка)",
        "standard_scholarship_1": "Поздравляем! Вы получаете стипендию.",
        "standard_scholarship_2": "Стипендия у ваших ног, молодец!",
        "standard_scholarship_comment_easy": " (хороший шанс)",
        "standard_scholarship_comment_hard": " (очень высокая планка)",
        "standard_scholarship_comment_medium": " (серьёзная подготовка)",
        "subject": "Предмет",
        "subject_name": "Название предмета {number}",
        "subjects_count": "Количество предметов:",
        "success_high_scholarship": "💎 Превосходно! Повышенная стипендия!",
        "success_scholarship": "✅ Успех! Обычная стипендия!",
        "support_button": "Поддержать автора",
        "support_description": "❤️ GradeMaster — бесплатный некоммерческий проект для студентов",
        "support_title": "🤝 Поддержка проекта",
        "support_warning": "Это добровольная поддержка некоммерческого проекта. Все калькуляторы остаются полностью бесплатными.",
        "template_add_assignment": "+ Добавить Assignment",
        "template_add_exam": "+ Добавить Exam",
        "template_add_quiz": "+ Добавить Quiz",
        "template_assignments_title": "📝 Assignments",
        "template_calculate_btn": "Рассчитать итоговую оценку",
        "template_copy_preset_btn": "Скопировать",
        "template_current_weight_label": "Текущая сумма весов:",
        "template_exams_title": "📊 Midterm/Endterm",
        "template_excellent": "Отлично!",
        "template_excellent_comment": "Превосходный результат!",
        "template_good": "Хорошо",
        "template_good_comment": "Курс успешно сдан!",
        "template_grade_placeholder": "Оценка (0-100)",
        "template_overall_result": "Общий результат:",
        "template_preset_copied": "✅ Ссылка скопирована.",
        "template_preset_corrupted": "❌ Ссылка на пресет повреждена или устарела.",
        "template_preset_create_error": "❌ Не получилось создать ссылку на пресет.",
        "template_preset_description": "Сохраните веса и список работ в ссылку. Оценки в пресет не попадают.",
        "template_preset_header": "🔗 Пресет предмета",
        "template_preset_loaded": "📥 Пресет загружен из ссылки.",
        "template_preset_saved": "✅ Пресет сохранён. Ссылку можно отправить другому человеку.",
        "template_quizzes_title": "📋 Quizzes",
        "template_satisfactory": "Удовлетворительно",
        "template_satisfactory_comment": "Курс сдан, но есть куда расти",
        "template_save_preset_btn": "Сохранить пресет",
        "template_sum_warning": "⚠️ Важно: Сумма весов всех секций должна быть равна 100%",
        "template_totals": "📈 Итоговые значения",
        "template_totals_header": "📈 Итоговые значения",
        "template_unsatisfactory": "Неудовлетворительно",
        "template_unsatisfactory_comment": "Необходима пересдача",
        "template_weight_label": "Вес:",
        "term_credits_placeholder": "Кредиты",
        "term_gpa_placeholder": "GPA триместра",
        "terms_count": "Количество триместров:",
        "thank_you": "🙏 Спасибо за вашу поддержку!",
        "theme_label": "Тема",
        "total_details": "РегТерм: {regterm}{source} | Итого: {total}",
        "warning_pass": "⚠️ Без стипендии",
        "warning_text": "⚠️ Важно: Списывание ведёт к отчислению!",
        "weight": "Вес:",
        "weight_current": "Текущая сумма весов:",
        "weight_warning": "⚠️ Сумма весов всех секций должна быть равна 100%.",
        "welcome": "Добро пожаловать в GradeMaster!",
        "yoomoney_title": "💰 ЮMoney (Яндекс.Деньги)",
        "yoomoney_wallet": "Кошелек:"
},

    'kk': {
        "add_assignment": "+ Тапсырма қосу",
        "add_exam": "+ Емтихан қосу",
        "add_quiz": "+ Тест қосу",
        "already_failed_1": "Қазіргі нәтижелермен курстан өту мүмкін емес.",
        "already_failed_2": "Қорытынды емтиханнан ең жоғары балл алсаңыз да, жағдай өзгермейді.",
        "assignment": "Тапсырма",
        "assignments": "Тапсырмалар",
        "att_allowed_miss_text": "Сіз <span class=\"highlight\">{missed}</span> сабақтан қалдыра аласыз.",
        "att_allowed_percentage": "Рұқсат етілген қалдыру пайызы:",
        "att_calc_completed": "✅ Есептеу аяқталды",
        "att_calc_step1": "1. 10 аптадағы барлық сабақ саны:",
        "att_calc_step2": "2. Рұқсат етілген қалдыру пайызы:",
        "att_calc_step3": "3. Есептеу:",
        "att_calc_step4": "4. Бүтін санға дейін дөңгелектеу:",
        "att_calculation": "Есептеу:",
        "att_description": "Бұл калькулятор семестрдің 10 аптасында қанша сабақты босатуға болатынын көрсетеді.",
        "att_done": "✅ Есептеу аяқталды",
        "att_error": "Қате",
        "att_how": "Есептеу жолы:",
        "att_how_calculated": "Бұл қалай есептеледі:",
        "att_lessons_label": "Апталық сабақ саны (бір сабақ — 50 минут):",
        "att_lessons_placeholder": "1-ден 20-ға дейінгі санды енгізіңіз",
        "att_missed": "Босатуға болатын сабақ саны: {count}.",
        "att_note": "Ескерту: Рұқсат етілетін босатулар саны пәнге байланысты өзгеруі мүмкін. Осы курстың силлабусын тексеріңіз.",
        "att_note_prefix": "Ескерту:",
        "att_percentage": "Рұқсат етілетін босатулар пайызы:",
        "att_placeholder": "1 мен 20 аралығындағы бүтін санды енгізіңіз",
        "att_please_enter": "Апталық сабақ санын енгізіңіз.",
        "att_range_error": "Сабақ саны 1 мен 20 аралығындағы бүтін сан болуы керек.",
        "att_rounding": "Бүтін санға дейін төмен дөңгелектеу:",
        "att_summary": "Аптасына {weekly} сабақ болғанда, 10 апта ішінде:",
        "att_summary_text": "10 апталық семестрде аптасына <span class=\"highlight\">{lessons}</span> сабақ болғанда:",
        "att_total": "10 аптадағы жалпы сабақ саны:",
        "bank_details": "Деректемелер:",
        "bank_title": "💳 Банк аударымы",
        "calculate_btn": "Есептеу",
        "calculate_cumulative": "Орташа GPA есептеу",
        "calculate_gpa": "GPA есептеу",
        "calculate_gpa_btn": "GPA есептеу",
        "calculate_total": "Қорытынды бағаны есептеу",
        "calculator_title": "📚 Баға калькуляторы",
        "component": "Жұмыс",
        "convert_btn": "GPA-ға түрлендіру",
        "converter_button": "Баға түрлендіргіші",
        "converter_description": "Пайыздық бағаны GPA-ға түрлендіру",
        "converter_title": "🔄 Бағаны GPA-ға түрлендіру",
        "copy_btn": "Көшіру",
        "copy_button": "Көшіру",
        "copy_error": "Көшіру мүмкін болмады. Сілтемені қолмен көшіріңіз.",
        "critical_check": "Негізгі шарттарды тексеру",
        "cumulative_count_error": "Триместр санын 1 мен 20 аралығындағы бүтін санмен енгізіңіз.",
        "cumulative_credits": "Кредиттер",
        "cumulative_data_error": "GPA 0 мен 4 аралығында, кредиттер 0-ден көп болуы керек.",
        "cumulative_desc": "Әр триместрдің GPA мәні мен кредиттерін енгізіңіз",
        "cumulative_error_count": "❌ Триместрлер санын дұрыс енгізіңіз (1-20)",
        "cumulative_error_insufficient": "❌ Есептеу үшін деректер жеткіліксіз.",
        "cumulative_error_validate": "❌ Енгізілген деректерді тексеріңіз. GPA 0 мен 4 арасында, кредиттер 0-ден көп болуы керек.",
        "cumulative_gpa": "GPA",
        "cumulative_results": "📋 Есептеу нәтижелері",
        "cumulative_term": "Триместр",
        "cumulative_title": "📈 Орташа GPA калькуляторы",
        "cumulative_total": "Жалпы GPA (орташа өлшенген):",
        "cumulative_warning": "⚠️ Барлық триместр бойынша дұрыс дерек енгізіңіз!",
        "cumulative_weighted": "GPA × Кредиттер",
        "current_mode": "Ағымдағы режим:",
        "custom_amount": "Басқа сома",
        "danger_fail": "❌ Жазғы семестр",
        "description": "Студенттерге арналған құралдар",
        "details_calculation": "Есептеу мәліметтері: РегТерм = {regterm}, қорытынды баға = {total}",
        "details_calculation_evil": "Мәліметтер: РегТерм = {regterm}, қорытынды = {total}",
        "details_calculation_standard": "РегТерм: {regterm}{source} | Қорытынды: {total}",
        "empty_msg_1": "Есептеуге қажетті барлық мәнді енгізіңіз.",
        "empty_msg_2": "Нақты нәтиже үшін барлық өрісті толтырыңыз.",
        "endterm": "Қорытынды бақылау",
        "error_empty": "❌ Есептеуге қажетті барлық мәнді енгізіңіз.",
        "error_invalid": "❌ Қате: Барлық баға 0 мен 100 аралығында болуы керек",
        "evil_advice_lucky": "💡 Кеңес: Бұл жолы жолың болды >:)",
        "evil_advice_memes": "💡 Кеңес: Мемдер қарағанша көбірек оқу керек пе еді?",
        "evil_already_failed_1": "Қазіргі нәтижелерің көңіл көншітпейді.",
        "evil_already_failed_2": "Емтиханнан 100 алсаң да көмектеспейді. Жазғы семестр күтіп тұр.",
        "evil_empty_1": "Сандарды енгізуді шынымен ұмыттың ба? Мұны да түсіндіру керек пе?",
        "evil_empty_2": "Ештеңе енгізілмеген. Шынымен бе?",
        "evil_fail_1": "Жазғы семестр. Жылама, мен тек есептедім. Қайта тапсыруда кездесеміз!",
        "evil_fail_2": "Өте алмадың. Әйтеуір, бұл күтілген еді.",
        "evil_high_1": "Керемет нәтиже! Сен де бірдеңе істей алады екенсің.",
        "evil_high_2": "Таңғалдырдың! Жалғастыра бер.",
        "evil_high_scholarship_1": "Шынымен бе? Жоғарылатылған шәкіртақы? Көшірмегеніңе сенімдісің бе?",
        "evil_high_scholarship_2": "Сенен мұны күтпеп едім!",
        "evil_high_scholarship_comment_easy": " (Бұл мүмкін!)",
        "evil_high_scholarship_comment_fantasy": " (Дұға ете бер 🙏)",
        "evil_high_scholarship_comment_hard": " (БӘРІН жатта!)",
        "evil_impossible_high": "Жоғарылатылған стипендия? Мұндай бағалармен бе? Армандау тегін ғой! 😂",
        "evil_invalid_1": "Баға минус шексіздіктен 200-ге дейін емес, 0-ден 100-ге дейін. Математика оқыдың ба?",
        "evil_invalid_2": "Дерек қате. Сен осы курста оқисың ба өзі?",
        "evil_pass_1": "Аман қалдың. Әзер болса да. Ең төменгі нәтижемен құттықтаймын.",
        "evil_pass_2": "Әйтеуір өттің. Ғажайып деуге болады.",
        "evil_pass_comment_easy": " (Әбден мүмкін)",
        "evil_pass_comment_hard": " (Ого! Бұл ҚИЫН болады)",
        "evil_pass_comment_medium": " (Кітапханада тұруға дайындал)",
        "evil_scholarship_1": "Шәкіртақы құтты болсын! Бірінші күні кофеге жұмсап қойма.",
        "evil_scholarship_2": "Құттықтаймын, шәкіртақы сенікі!",
        "evil_scholarship_comment_fantasy": " (Бұл енді қиял әлемі!)",
        "evil_scholarship_comment_hard": " (Мүмкіндіктің шегінде!)",
        "evil_scholarship_comment_medium": " (Керемет күш салу керек)",
        "evil_tip_lucky": "💡 Кеңес: Бұл жолы жолың болды >:)",
        "evil_tip_study": "💡 Кеңес: Мем қарағанша көбірек оқу керек пе еді?",
        "exam": "Емтихан",
        "exams": "Емтихандар",
        "expired_link": "❌ Сілтеменің жарамдылық мерзімі аяқталды",
        "failed_title": "❌ Жазғы семестр",
        "feature_all_subjects": "• Кез келген пәнге жарайды",
        "feature_clear_method": "• Түсінікті есептеу әдісі",
        "feature_cumulative1": "• Кредит санының айырмашылығын ескеру",
        "feature_cumulative2": "• 20 триместрге дейін",
        "feature_cumulative3": "• Үтірден кейін екі таңба",
        "feature_fast_start": "• Жылдам бастау",
        "feature_manual": "• Барлық мәнді қолмен енгізу",
        "feature_popular_subjects": "• Кең таралған пәндер",
        "feature_preset_weights": "• Алдын ала қойылған салмақтар",
        "feature_readable_interface": "• Түсінікті интерфейс",
        "feature_transparency": "• Есептеу барысы толық көрсетіледі",
        "feedback_anonymous": "Анонимді қолданушы",
        "feedback_contact": "Байланыс деректері (жауап қажет болса):",
        "feedback_contact_label": "Байланыс дерегі (жауап қажет болса):",
        "feedback_contact_placeholder": "Telegram, email немесе басқа",
        "feedback_cooldown_notice": "Күте тұрыңыз. Келесі хабарламаны {time} кейін жібере аласыз.",
        "feedback_cooldown_prefix": "Қайта жіберу уақыты",
        "feedback_description": "Калькуляторды жақсарту идеяңыз бар ма немесе қате таптыңыз ба? Бізге жазыңыз — пікіріңіз біз үшін маңызды!",
        "feedback_draft_restored": "✅ Хабарлама мәтіні қалпына келтірілді!",
        "feedback_error": "Хабарламаны жіберу қатесі",
        "feedback_error_try_again": "❌ Қате орын алды. Қайталап көріңіз.",
        "feedback_from": "Кімнен:",
        "feedback_invalid": "Хабарламаны өңдеу мүмкін болмады. Бетті жаңартып, қайталап көріңіз.",
        "feedback_limits": "Хабарламада 3000, есімде 100, байланыс деректерінде 200 таңбаға дейін.",
        "feedback_message": "Хабарлама:*",
        "feedback_message_label": "Хабарлама:*",
        "feedback_message_placeholder": "Идеяңызды, мәселеңізді немесе ұсынысыңызды сипаттаңыз...",
        "feedback_name": "Атыңыз (міндетті емес):",
        "feedback_name_label": "Атыңыз (міндетті емес):",
        "feedback_name_placeholder": "Сізге қалай жүгінейік?",
        "feedback_network_error": "Сервермен байланысу мүмкін болмады. Интернет байланысын тексеріңіз. Енгізілген мәтін формада қалды.",
        "feedback_rate_limited": "Сұраулар тым көп. Қайта жібермес бұрын сәл күтіңіз.",
        "feedback_required": "Жіберу үшін хабарлама енгізіңіз.",
        "feedback_restore_btn": "↩️ Хабарлама мәтінін қайтару",
        "feedback_sending": "Жіберілуде...",
        "feedback_source": "Дереккөз:",
        "feedback_submit": "📨 Хабарлама жіберу",
        "feedback_submit_btn": "📨 Хабарлама жіберу",
        "feedback_subtitle": "Калькуляторды жақсарту бойынша идеяларыңыз бар ма? Қате таптыңыз ба?<br>Бізге жазыңыз — біз сіздің пікіріңізді бағалаймыз!",
        "feedback_success": "Пікіріңізге рақмет!",
        "feedback_success_contact": "Жақын арада хабарласамыз!",
        "feedback_time": "Уақыты:",
        "feedback_timeout": "Сервер жіберуді уақытында растамады. Хабарлама жеткізілген болуы мүмкін. Енгізілген мәтін формада қалды.",
        "feedback_too_long": "Мәтінді қысқартыңыз: хабарламада 3000, есімде 100, байланыс деректерінде 200 таңбаға дейін.",
        "feedback_type": "Хабарлама түрі:",
        "feedback_type_bug": "Қате туралы хабарлама",
        "feedback_type_feature": "Жаңа функцияға сұрау",
        "feedback_type_label": "Өтініш түрі:",
        "feedback_type_other": "Басқа",
        "feedback_type_suggestion": "Ұсыныс",
        "feedback_unavailable": "Кері байланыс уақытша қолжетімсіз. Кейінірек қайталап көріңіз — енгізілген мәтін формада қалды.",
        "feedback_user_anonymous": "Анонимді пайдаланушы",
        "final_label": "Қорытынды емтихан (0–100)",
        "final_placeholder": "Болжам үшін бос қалдырыңыз",
        "footer_copyright": "© 2025 Not_404. Қате тапсаңыз, Telegram арқылы хабарласыңыз",
        "for_high_scholarship": "Жоғарылатылған шәкіртақы үшін:",
        "for_high_scholarship_title": "💎 Жоғарылатылған стипендия үшін:",
        "for_pass": "Курстан өту үшін:",
        "for_pass_title": "📝 Курстан өту үшін:",
        "for_regular_scholarship": "Қалыпты шәкіртақы үшін:",
        "for_scholarship_title": "💰 Қарапайым стипендия үшін:",
        "generate_qr": "✨ QR-код жасау",
        "generate_subjects": "Пәндерге арналған өрістерді жасау",
        "generate_terms": "Өрістерді жасау",
        "go_button": "Ашу",
        "gpa_button": "GPA калькуляторы",
        "gpa_calc_results_title": "📋 Есептеу нәтижелері",
        "gpa_correct_count": "Пән санын дұрыс енгізіңіз (1–20 аралығындағы бүтін сан)",
        "gpa_credits_col": "Кредиттер",
        "gpa_credits_placeholder": "Кредиттер",
        "gpa_description": "Кредиттерді ескеріп, орташа өлшенген GPA есептеу",
        "gpa_fill_all": "Енгізілген деректерді тексеріңіз. Барлық өріс дұрыс толтырылуы керек.",
        "gpa_formula": "GPA = Σ(пәннің GPA мәні × кредиттер) / Σ(кредиттер)",
        "gpa_gpa_col": "GPA",
        "gpa_grade_col": "Баға (%)",
        "gpa_grade_placeholder": "Баға (%)",
        "gpa_insufficient": "Есептеуге дерек жеткіліксіз. Кредиті мен бағасы бар кемінде бір пән қосыңыз.",
        "gpa_item_prefix": "Пән",
        "gpa_overall": "Жалпы GPA (орташа өлшенген):",
        "gpa_subject_col": "Пән",
        "gpa_subject_name": "Пән атауы",
        "gpa_title": "📊 GPA калькуляторы",
        "gpa_warning": "⚠️ Маңызды: Барлық пән бойынша дұрыс дерек енгізіңіз!",
        "gpa_weighted_col": "GPA × Кредиттер",
        "grade_percentage": "Баға (%)",
        "grade_range": "Баға (0–100)",
        "high_comment_easy": " (қиын, бірақ мүмкін)",
        "high_comment_hard": " (мүмкін емес деуге болады)",
        "high_impossible": "Қазіргі нәтижелермен жоғарылатылған шәкіртақы алу мүмкін емес.",
        "high_impossible_evil": "Жоғарылатылған шәкіртақы? Мына бағалармен бе? Армандауға болады! 😂",
        "high_scholarship_title": "💎 Тамаша! Жоғарылатылған шәкіртақы!",
        "higher_scholarship": "Жоғарылатылған шәкіртақы алу мүмкін емес",
        "important_info": "ℹ️ Маңызды ақпарат:",
        "impossible_pass": "Мүмкін емес ({value} > 100 балл қажет)",
        "impossible_scholarship": "100-ден көп балл керек. Пара беріп көресің бе? Әзіл ғой... әлде жоқ па 🤔",
        "impossible_scholarship_evil": "100-ден көп балл керек. Пара беріп көресің бе? Әзіл ғой... әлде жоқ па 🤔",
        "impossible_scholarship_serious": "Қазіргі нәтижелермен шәкіртақы алу мүмкін емес.",
        "impossible_scholarship_standard": "Қазіргі нәтижелермен шәкіртақы алу мүмкін емес.",
        "invalid_link": "❌ Сілтеме жарамсыз немесе ескірген",
        "invalid_msg_1": "0 мен 100 аралығындағы дұрыс мәндерді енгізіңіз.",
        "invalid_msg_2": "Дерек қате, бағалар ауқымын тексеріңіз.",
        "kaspi_card": "Карта нөмірі:",
        "kaspi_title": "🇰🇿 Kaspi аударымы",
        "language_label": "Тіл",
        "link_copied": "✅ Сілтеме көшірілді.",
        "main_description": "Калькулятор түрін таңдаңыз",
        "main_title": "GradeMaster — Басты бет",
        "midterm": "Аралық бақылау",
        "minimum_points": "Кемінде {value} балл",
        "mode_evil": "Қатал жоғары курс студенті",
        "mode_evil_msg": "Қатал жоғары курс студенті режимі.",
        "mode_serious": "Байыпты режим",
        "mode_serious_msg": "Байыпты талдаушы режимі.",
        "mode_standard": "Стандартты режим",
        "mode_standard_msg": "Стандартты режим. Бәрі нақты.",
        "nav_evil": "Қатал жоғары курс студенті",
        "nav_feedback": "💬 Кері байланыс",
        "nav_home": "← Басты бет",
        "nav_language": "Тіл",
        "nav_mode": "Режимді ауыстыру",
        "nav_serious": "Байыпты режим",
        "nav_standard": "Стандартты режим",
        "nav_theme": "🌙 Тақырып",
        "option_att_desc": "Сабаққа қатысуды бақылау және есептеу",
        "option_att_title": "📋 Сабаққа қатысу калькуляторы",
        "option_attendance_desc": "Сабаққа қатысуыңызды есептеуге арналған ыңғайлы құрал",
        "option_attendance_title": "📚 Сабаққа қатысу калькуляторы",
        "option_converter_desc": "Пайыздық бағаны GPA-ға түрлендіру",
        "option_converter_title": "🔄 Бағаны GPA-ға түрлендіру",
        "option_cumulative_desc": "Бірнеше триместрдің кредиттерін ескеріп, жалпы GPA есептеңіз",
        "option_cumulative_title": "📈 Триместрлер бойынша орташа GPA",
        "option_feedback_desc": "Қолданбаны жақсартуға көмектесіңіз",
        "option_feedback_title": "💬 Кері байланыс",
        "option_gpa_desc": "Бағаларыңыз бойынша GPA есептеңіз",
        "option_gpa_title": "📊 Қорытынды GPA калькуляторы",
        "option_templates_desc": "Кең таралған пәндерге арналған дайын баптаулар",
        "option_templates_title": "📚 Пән үлгілері",
        "option_total_desc": "Емтиханға қаншалықты дайындалу керегін есептеңіз",
        "option_total_title": "🚀 Қорытынды баға калькуляторы",
        "page_title_attendance": "Сабаққа қатысу калькуляторы — GradeMaster",
        "page_title_cumulative": "Орташа GPA — GradeMaster",
        "page_title_feedback": "GradeMaster — Кері байланыс",
        "page_title_gpa": "GPA калькуляторы — GradeMaster",
        "page_title_template": "Пән үлгілері — GradeMaster",
        "page_title_total": "GradeMaster — Баға калькуляторы",
        "pass_msg_1": "Курстан өттіңіз. Қорытынды баға талапқа сай.",
        "pass_msg_2": "Курсты сәтті аяқтадыңыз, құттықтаймыз!",
        "pass_title": "⚠️ Шәкіртақысыз",
        "percentage_label": "Қорытынды баға (%):",
        "percentage_placeholder": "Мысалы: 85",
        "prediction_msg_1": "Қажетті балдарды есептеу:",
        "prediction_msg_2": "Қорытынды емтиханнан қанша балл алу керек:",
        "prediction_title": "🔮 Болжам",
        "preset_description": "Салмақтар мен жұмыстар тізімін сілтемеге сақтаңыз. Бағалар сақталмайды.",
        "preset_error": "❌ Баптаулар сілтемесін жасау мүмкін болмады.",
        "preset_invalid": "❌ Баптаулар сілтемесі бүлінген немесе ескірген.",
        "preset_link_label": "Пән баптауларының сілтемесі",
        "preset_loaded": "📥 Баптаулар сілтемеден жүктелді.",
        "preset_save": "Баптауларды сақтау",
        "preset_saved": "✅ Баптаулар сақталды. Сілтемені басқа адамға жіберуге болады.",
        "preset_title": "🔗 Пән баптаулары",
        "qr_description": "Деректемелері толтырылған Kaspi қолданбасын ашу үшін QR-кодты сканерлеңіз:",
        "quick_transfer": "📱 Kaspi арқылы жылдам аударым",
        "quiz": "Тест",
        "quizzes": "Тесттер",
        "regend_below_25_evil": "РегЭнд < 25... Біреу маңызды дәрістерді өткізіп алған сияқты. Әлде бәрін бе?",
        "regend_below_25_serious": "РегЭнд ең төменгі шектен төмен. Курстан өту мүмкін емес.",
        "regend_below_25_standard": "РегЭнд 25-тен төмен. Жазғы семестрден басқа жол жоқ.",
        "regend_label": "РегЭнд (0–100)",
        "regend_placeholder": "Бағаны енгізіңіз",
        "regmid_below_25": "РегМид < 25? Шынымен бе? Сабаққа бардың ба өзі? 💀",
        "regmid_below_25_standard": "РегМид 25-тен төмен. Жазғы семестрден басқа жол жоқ.",
        "regmid_below_minimum": "РегМид ең төменгі шектен төмен. Курстан өту мүмкін емес.",
        "regmid_label": "РегМид (0–100)",
        "regmid_placeholder": "Бағаны енгізіңіз",
        "regterm_below_50": "РегТерм < 50. Құттықтаймын, емтиханға жетпей жатып жазғы семестрге қалдың!",
        "regterm_below_50_serious": "РегТерм ең төменгі шектен төмен. Курстан өту мүмкін емес.",
        "regterm_below_50_standard": "РегТерм 50-ден төмен. Жазғы семестрден құтылу мүмкін емес.",
        "regterm_calculated": " (РегМид пен РегЭнд бойынша есептелді)",
        "regterm_direct_input": " (тікелей енгізілді)",
        "regterm_display": "РегТерм: {value}{source}",
        "regterm_label": "РегТерм (0–100)",
        "regterm_placeholder": "Немесе РегТерм мәнін тікелей енгізіңіз",
        "regterm_source_calc": " (РегМид пен РегЭндтен есептелген)",
        "remove_item": "Жолды жою",
        "retake_evil": "Емтихан балы 25 пен 50 аралығында. Тағдыр екінші мүмкіндік берді, құр жіберме.",
        "retake_serious": "Емтихан тапсырылмады, бірақ қайта тапсыру мүмкіндігі бар.",
        "retake_standard": "Қайта тапсыру. Сізде екінші мүмкіндік бар.",
        "retake_title": "⚠️ Қайта тапсыру",
        "scholarship_title": "✅ Құттықтаймыз! Қалыпты шәкіртақы!",
        "secret_auto_passing": "Емтиханнан автоматты өту функциясы әлі әзірленіп жатыр...",
        "secret_calculator_scholarship": "Бұл калькулятор студент болса, шәкіртақы алар еді!",
        "secret_calculator_student": "Бұл калькулятор неге дәл есептейді? Ол емтиханда көшірмеген!",
        "secret_difference": "Студент пен калькулятордың айырмасы қандай? Калькулятор әрқашан дұрыс есептейді!",
        "secret_easter_egg": "Құпия іздеуші, құттықтаймын! Басқа беттерде де бірдеңе бар шығар?)",
        "secret_excuse": "Құттықтаймыз! Емтиханға дайындалмауға сылтау таптыңыз!",
        "secret_extra_1": "Құпия! Жасырын хабарламаны таптың! 🥚",
        "secret_extra_10": "Автор осында болды 🐛",
        "secret_extra_11": "Бұл хабарлама 5... 4... 3... секундтан кейін жойылады... әзіл!",
        "secret_extra_12": "«Оқуым керек еді, бірақ құпия іздеп жүрмін» деңгейіндегі хабарлама",
        "secret_extra_13": "Ішкі ақпарат: оқытушылар да калькулятор қолданады!",
        "secret_extra_14": "Жақсы бағаның құпиясы — сенімділік (және осы калькулятор)",
        "secret_extra_15": "«Сабақты автоматты босату» функциясы уақытша өшірілген... өкінішке қарай",
        "secret_extra_16": "Калькулятор мен жақсы бағаның ортақ қасиеті қандай? Екеуіне де дұрыс бастапқы дерек қажет!",
        "secret_extra_17": "Назар аударыңыз! Калькуляторды қолдану мен үрейдің азаюы арасында байланыс бар!",
        "secret_extra_2": "Бұл калькулятордың авторы да кейде емтиханнан өте алмайды 😅",
        "secret_extra_3": "Алғашқы калькулятордың XVII ғасырда жасалғанын білесің бе?",
        "secret_extra_4": "Бұл калькулятор ♥ және көп кофемен жасалды ☕",
        "secret_extra_5": "Қызық дерек: студенттердің 87%-ы емтиханға дайындалғанда құпия хабарлама табады",
        "secret_extra_6": "Тсс... арамызда қалсын, РегМид салмағы 30%, бірақ бәрі білмегендей болады",
        "secret_extra_7": "Автор кеңесі: күніне бір құпия хабарлама — сессиядан қорықпайсың!",
        "secret_extra_8": "Дерек: бұл калькуляторды қолданушылардың 100%-ы оқудан сәтті алаңдайды!",
        "secret_extra_9": "Құпия формула: ұйқы + тамақ + осы калькулятор = сәтті сессия!",
        "secret_hack": "Хакер кеңесі: емтиханнан өту үшін оған бару керек 😉",
        "secret_leak": "Назар аударыңыз! Құпия ашылды: емтихан бағаның 40%-ын құрайды!",
        "secret_manual_check": "Құпия кеңес: есептеулерді әрқашан қолмен тексеріңіз!",
        "secret_rare_user": "Сіз осы құпияны тапқан 1000 қолданушының бірісіз!",
        "secret_subtitle": "👀 Жасырын мағына іздеп жүрсің бе? Ол жоқ!",
        "secret_success": "Табыс сыры: 10% сәттілік, 20% дағды, 70% осы калькулятор!",
        "secret_theme": "🎨 Суретшісің бе? Тақырыптарды тез ауыстырасың!",
        "secret_triple": "🎉 Үш рет басу! Сабақта ішің пысқан сияқты!",
        "secret_warning": "Ескерту: калькуляторды жиі қолдану... жақсы бағаға әкелуі мүмкін!",
        "select_amount": "Соманы таңдаңыз (₸):",
        "serious_impossible_high": "Ағымдағы нәтижелермен жоғарылатылған стипендия алу мүмкін емес.",
        "serious_pass_comment": "",
        "serious_scholarship_comment_easy": " (қиындық деңгейі жоғары)",
        "serious_scholarship_comment_hard": " (аса қиын)",
        "serious_scholarship_comment_medium": " (қиындық деңгейі өте жоғары)",
        "share_button": "🔗 Досыңызға сілтеме жасау",
        "share_copied_success": "✅ Сілтеме алмасу буферіне көшірілді!",
        "share_created": "✅ Сілтеме жасалды! Ол 24 сағат бойы жарамды.",
        "share_created_success": "✅ Сілтеме жасалды! Деректер сілтемеде сақталды.",
        "share_data_loaded": "📥 Деректер ортақ сілтемеден жүктелді!",
        "share_info": "Бұл сілтеме 24 сағат бойы жарамды және енгізілген барлық деректі сақтайды",
        "share_link_label": "Бөлісу сілтемесі:",
        "share_loaded": "📥 Деректер бөлісу сілтемесінен жүктелді!",
        "sigma_credits": "Σ(кредиттер)",
        "sigma_gpa_credits": "Σ(GPA × кредиттер)",
        "standard_empty_1": "Есептеу үшін барлық өрісті толтырыңыз.",
        "standard_empty_2": "Барлық бағаны енгізуді ұмытпаңыз.",
        "standard_fail_1": "Өкінішке қарай, нәтиже өту балынан төмен.",
        "standard_fail_2": "Жазғы семестрден құтыла алмайсыз, қайта тапсыруға дайындалыңыз.",
        "standard_high_1": "Керемет нәтиже! Біліміңіз жоғары деңгейде.",
        "standard_high_2": "Тамаша! Осы қарқыннан таймаңыз.",
        "standard_high_scholarship_1": "Тамаша! Сізге жоғарылатылған шәкіртақы беріледі!",
        "standard_high_scholarship_2": "Жоғары нәтиже! Жоғарылатылған шәкіртақы!",
        "standard_high_scholarship_comment_easy": " (қиын, бірақ мүмкін)",
        "standard_high_scholarship_comment_hard": " (мүмкін емес дерлік)",
        "standard_high_scholarship_comment_medium": " (өте қиын)",
        "standard_invalid_1": "Бағалар 0 мен 100 аралығында болуы керек.",
        "standard_invalid_2": "Мән қате, ауқымды тексеріңіз.",
        "standard_pass_1": "Курстан өттіңіз. Қорытынды баға талапқа сай.",
        "standard_pass_2": "Курсты сәтті аяқтадыңыз, құттықтаймыз!",
        "standard_pass_comment_easy": " (қол жеткізуге болады)",
        "standard_pass_comment_hard": " (өте қиын)",
        "standard_pass_comment_medium": " (жақсы дайындық қажет)",
        "standard_scholarship_1": "Құттықтаймыз! Сізге шәкіртақы беріледі.",
        "standard_scholarship_2": "Шәкіртақы сіздікі, жарайсыз!",
        "standard_scholarship_comment_easy": " (жақсы мүмкіндік)",
        "standard_scholarship_comment_hard": " (өте жоғары меже)",
        "standard_scholarship_comment_medium": " (тиянақты дайындық)",
        "subject": "Пән",
        "subject_name": "Пән атауы {number}",
        "subjects_count": "Пәндер саны:",
        "success_high_scholarship": "💎 Тамаша! Жоғарылатылған шәкіртақы!",
        "success_scholarship": "✅ Құттықтаймыз! Қалыпты шәкіртақы!",
        "support_button": "Авторды қолдау",
        "support_description": "❤️ GradeMaster — студенттерге арналған тегін коммерциялық емес жоба",
        "support_title": "🤝 Жобаны қолдау",
        "support_warning": "Бұл — коммерциялық емес жобаны ерікті түрде қолдау. Барлық калькулятор тегін болып қалады.",
        "template_add_assignment": "+ Assignment қосу",
        "template_add_exam": "+ Exam қосу",
        "template_add_quiz": "+ Quiz қосу",
        "template_assignments_title": "📝 Assignments (Тапсырмалар)",
        "template_calculate_btn": "Қорытынды бағаны есептеу",
        "template_copy_preset_btn": "Көшіріп алу",
        "template_current_weight_label": "Ағымдағы салмақтар қосындысы:",
        "template_exams_title": "📊 Midterm/Endterm (Емтихандар)",
        "template_excellent": "Өте жақсы!",
        "template_excellent_comment": "Керемет нәтиже!",
        "template_good": "Жақсы",
        "template_good_comment": "Курс сәтті аяқталды!",
        "template_grade_placeholder": "Баға (0-100)",
        "template_overall_result": "Жалпы нәтиже:",
        "template_preset_copied": "✅ Сілтеме көшірілді.",
        "template_preset_corrupted": "❌ Пресет сілтемесі бүлінген немесе ескірген.",
        "template_preset_create_error": "❌ Пресет сілтемесін жасау мүмкін болмады.",
        "template_preset_description": "Салмақтар мен жұмыстар тізімін сілтемеге сақтаңыз. Бағалар пресетке кірмейді.",
        "template_preset_header": "🔗 Пән пресеті",
        "template_preset_loaded": "📥 Пресет сілтемеден жүктелді.",
        "template_preset_saved": "✅ Пресет сақталды. Сілтемені басқа адамға жіберуге болады.",
        "template_quizzes_title": "📋 Quizzes (Квиздер)",
        "template_satisfactory": "Қанағаттанарлық",
        "template_satisfactory_comment": "Курстан өттіңіз, бірақ нәтижені жақсартуға болады",
        "template_save_preset_btn": "Пресетті сақтау",
        "template_sum_warning": "⚠️ Маңызды: Барлық бөлімдер салмағының қосындысы 100% болуы керек",
        "template_totals": "📈 Қорытынды мәндер",
        "template_totals_header": "📈 Қорытынды мәндер",
        "template_unsatisfactory": "Қанағаттанарлықсыз",
        "template_unsatisfactory_comment": "Қайта тапсыру қажет",
        "template_weight_label": "Салмағы:",
        "term_credits_placeholder": "Кредиттер",
        "term_gpa_placeholder": "Триместр GPA мәні",
        "terms_count": "Триместрлер саны:",
        "thank_you": "🙏 Қолдауыңызға рақмет!",
        "theme_label": "Тақырып",
        "total_details": "РегТерм: {regterm}{source} | Қорытынды: {total}",
        "warning_pass": "⚠️ Шәкіртақысыз",
        "warning_text": "⚠️ Маңызды: Көшіру оқудан шығаруға әкеледі!",
        "weight": "Салмақ:",
        "weight_current": "Салмақтардың ағымдағы қосындысы:",
        "weight_warning": "⚠️ Барлық бөлім салмақтарының қосындысы 100% болуы керек.",
        "welcome": "GradeMaster-ге қош келдіңіз!",
        "yoomoney_title": "💰 ЮMoney (Яндекс.Ақша)",
        "yoomoney_wallet": "Әмиян:"
},

    'en': {
        "add_assignment": "+ Add assignment",
        "add_exam": "+ Add exam",
        "add_quiz": "+ Add quiz",
        "already_failed_1": "Based on current results, passing is impossible.",
        "already_failed_2": "Even a perfect final will not save the situation.",
        "assignment": "Assignment",
        "assignments": "Assignments",
        "att_allowed_miss_text": "You can miss <span class=\"highlight\">{missed}</span> classes.",
        "att_allowed_percentage": "Allowed absence percentage:",
        "att_calc_completed": "✅ Calculation complete",
        "att_calc_step1": "1. Total classes in 10 weeks:",
        "att_calc_step2": "2. Allowed absence percentage:",
        "att_calc_step3": "3. Calculation:",
        "att_calc_step4": "4. Rounding to whole number:",
        "att_calculation": "Calculation:",
        "att_description": "Calculate how many classes you can miss over 10 weeks.",
        "att_done": "✅ Calculation complete",
        "att_error": "Error",
        "att_how": "How this is calculated:",
        "att_how_calculated": "How it is calculated:",
        "att_lessons_label": "Classes per week (one class is 50 minutes):",
        "att_lessons_placeholder": "Enter a number from 1 to 20",
        "att_missed": "Classes you may miss: {count}.",
        "att_note": "The actual number of allowed absences may depend on the specific subject, check the syllabus of this course.",
        "att_note_prefix": "Note:",
        "att_percentage": "Allowed absence percentage:",
        "att_placeholder": "Enter a whole number from 1 to 20",
        "att_please_enter": "Please enter the number of classes per week.",
        "att_range_error": "Number of classes must be from 1 to 20.",
        "att_rounding": "Rounded down to a whole number:",
        "att_summary": "Over 10 weeks with {weekly} classes per week:",
        "att_summary_text": "Over 10 weeks of semester with <span class=\"highlight\">{lessons}</span> classes per week:",
        "att_total": "Total classes over 10 weeks:",
        "bank_details": "Details:",
        "bank_title": "💳 Bank transfer",
        "calculate_btn": "Calculate",
        "calculate_cumulative": "Calculate cumulative GPA",
        "calculate_gpa": "Calculate GPA",
        "calculate_gpa_btn": "Calculate GPA",
        "calculate_total": "Calculate final grade",
        "calculator_title": "📚 Grade Calculator",
        "component": "Component",
        "convert_btn": "Convert to GPA",
        "converter_button": "Grade Converter",
        "converter_description": "Convert percentage grade to GPA",
        "converter_title": "🔄 Grade to GPA Converter",
        "copy_btn": "Copy",
        "copy_button": "Copy",
        "copy_error": "Could not copy. Please copy the link manually.",
        "critical_check": "Critical conditions check",
        "cumulative_count_error": "Enter a whole number of trimesters from 1 to 20.",
        "cumulative_credits": "Credits",
        "cumulative_data_error": "GPA must be between 0 and 4, and credits greater than 0.",
        "cumulative_desc": "Calculate cumulative GPA across multiple trimesters",
        "cumulative_error_count": "❌ Please enter a valid number of trimesters (1-20)",
        "cumulative_error_insufficient": "❌ Insufficient data for calculation.",
        "cumulative_error_validate": "❌ Please check entered data. GPA must be 0-4, credits > 0.",
        "cumulative_gpa": "GPA",
        "cumulative_results": "📋 Calculation Results",
        "cumulative_term": "Trimester",
        "cumulative_title": "📊 Cumulative GPA Calculator",
        "cumulative_total": "Overall GPA (weighted):",
        "cumulative_warning": "⚠️ Enter valid data for every trimester!",
        "cumulative_weighted": "GPA × Credits",
        "current_mode": "Current mode:",
        "custom_amount": "Custom amount",
        "danger_fail": "❌ Failed",
        "description": "A set of tools for students",
        "details_calculation": "Calculation details: RegTerm = {regterm}, Final score = {total}",
        "details_calculation_evil": "Details: RegTerm = {regterm}, Total = {total}",
        "details_calculation_standard": "RegTerm: {regterm}{source} | Total: {total}",
        "empty_msg_1": "Please enter all values for calculation.",
        "empty_msg_2": "All fields must be filled for accurate results.",
        "endterm": "Endterm",
        "error_empty": "❌ Please enter all values for calculation.",
        "error_invalid": "❌ Error: All grades must be in range 0-100",
        "evil_advice_lucky": "💡 Tip: Lucky this time >:)",
        "evil_advice_memes": "💡 Tip: Maybe you should have studied more instead of scrolling memes?",
        "evil_already_failed_1": "Current results are not promising.",
        "evil_already_failed_2": "Even 100 on final will not help. Retake guaranteed.",
        "evil_empty_1": "Did you seriously forget to enter numbers? Or do I need to explain this too?",
        "evil_empty_2": "Nothing entered. Seriously?",
        "evil_fail_1": "Retake. Not painful, I just calculated. See you on retake!",
        "evil_fail_2": "You failed. At least it was predictable.",
        "evil_high_1": "Outstanding! At least you can do something right.",
        "evil_high_2": "Actually impressed. Keep going.",
        "evil_high_scholarship_1": "Seriously? Increased scholarship? You did not cheat?",
        "evil_high_scholarship_2": "Did not expect this from you!",
        "evil_high_scholarship_comment_easy": " (It's real!)",
        "evil_high_scholarship_comment_fantasy": " (Start praying 🙏)",
        "evil_high_scholarship_comment_hard": " (Study EVERYTHING!)",
        "evil_impossible_high": "Increased scholarship? With those grades? Keep dreaming! 😂",
        "evil_invalid_1": "Grades from 0 to 100, not from minus infinity to 200. Did you study math?",
        "evil_invalid_2": "Invalid data. Are you even in this course?",
        "evil_pass_1": "You barely passed. Congratulations on the minimum result.",
        "evil_pass_2": "Well, you did it. Almost a miracle.",
        "evil_pass_comment_easy": " (Quite real)",
        "evil_pass_comment_hard": " (Wow! This will be DIFFICULT)",
        "evil_pass_comment_medium": " (Get ready to live in the library)",
        "evil_scholarship_1": "You got a scholarship! Do not spend it on coffee on the first day.",
        "evil_scholarship_2": "Congratulations, scholarship is yours!",
        "evil_scholarship_comment_fantasy": " (This is already fantasy!)",
        "evil_scholarship_comment_hard": " (On the edge of possibility!)",
        "evil_scholarship_comment_medium": " (Incredible effort needed)",
        "evil_tip_lucky": "💡 Tip: You got lucky this time >:)",
        "evil_tip_study": "💡 Tip: Maybe spend more time studying than scrolling memes?",
        "exam": "Exam",
        "exams": "Exams",
        "expired_link": "❌ Link has expired",
        "failed_title": "❌ Retake",
        "feature_all_subjects": "• Works for any subject",
        "feature_clear_method": "• Clear counting method",
        "feature_cumulative1": "• Different credit counts",
        "feature_cumulative2": "• Up to 20 trimesters",
        "feature_cumulative3": "• Two decimal precision",
        "feature_fast_start": "• Quick start",
        "feature_manual": "• Manual entry of all parameters",
        "feature_popular_subjects": "• Popular subjects",
        "feature_preset_weights": "• Preset weights",
        "feature_readable_interface": "• Readable interface",
        "feature_transparency": "• Maximum transparency",
        "feedback_anonymous": "Anonymous user",
        "feedback_contact": "Contact (if you would like a reply):",
        "feedback_contact_label": "Contact (if reply needed):",
        "feedback_contact_placeholder": "Telegram, email, etc.",
        "feedback_cooldown_notice": "Please wait. You can send the next message in {time}.",
        "feedback_cooldown_prefix": "Resend in",
        "feedback_description": "Have ideas to improve the calculator or found a bug? Send us your feedback!",
        "feedback_draft_restored": "✅ Message draft restored!",
        "feedback_error": "Error sending message",
        "feedback_error_try_again": "❌ An error occurred. Please try again.",
        "feedback_from": "From:",
        "feedback_invalid": "The message could not be processed. Refresh the page and try again.",
        "feedback_limits": "Up to 3000 characters for the message, 100 for your name and 200 for contact details.",
        "feedback_message": "Message:*",
        "feedback_message_label": "Message:*",
        "feedback_message_placeholder": "Describe your idea, issue or suggestion...",
        "feedback_name": "Your name (optional):",
        "feedback_name_label": "Your name (optional):",
        "feedback_name_placeholder": "What should we call you?",
        "feedback_network_error": "Could not connect to the server. Check your internet connection. Your text is still in the form.",
        "feedback_rate_limited": "Too many requests. Please wait a little before sending again.",
        "feedback_required": "Enter a message before sending.",
        "feedback_restore_btn": "↩️ Restore message text",
        "feedback_sending": "Sending...",
        "feedback_source": "Source:",
        "feedback_submit": "📨 Send message",
        "feedback_submit_btn": "📨 Send message",
        "feedback_subtitle": "Have ideas to improve the calculator? Found a bug?<br>Contact us — we appreciate your feedback!",
        "feedback_success": "Thank you for your feedback!",
        "feedback_success_contact": "We will contact you soon!",
        "feedback_time": "Time:",
        "feedback_timeout": "The server did not confirm delivery in time. Your message may have been delivered. Your text is still in the form.",
        "feedback_too_long": "Shorten the text: up to 3000 characters for the message, 100 for your name and 200 for contact details.",
        "feedback_type": "Feedback type:",
        "feedback_type_bug": "🐛 Bug report",
        "feedback_type_feature": "🚀 Feature request",
        "feedback_type_label": "Feedback type:",
        "feedback_type_other": "📝 Other",
        "feedback_type_suggestion": "💡 Suggestion",
        "feedback_unavailable": "Feedback is temporarily unavailable. Try again later — your text is still in the form.",
        "feedback_user_anonymous": "Anonymous user",
        "final_label": "Final (0-100)",
        "final_placeholder": "Leave empty for prediction",
        "footer_copyright": "&copy; 2025 Not_404. In case of any bug contact via Telegram",
        "for_high_scholarship": "For increased scholarship:",
        "for_high_scholarship_title": "💎 For increased scholarship:",
        "for_pass": "To pass the course:",
        "for_pass_title": "📝 To pass the course:",
        "for_regular_scholarship": "For regular scholarship:",
        "for_scholarship_title": "💰 For regular scholarship:",
        "generate_qr": "✨ Generate QR code",
        "generate_subjects": "Generate form for subjects",
        "generate_terms": "Generate form for trimesters",
        "go_button": "Go",
        "gpa_button": "GPA Calculator",
        "gpa_calc_results_title": "📋 Calculation Results",
        "gpa_correct_count": "Please enter the correct number of subjects (1-20)",
        "gpa_credits_col": "Credits",
        "gpa_credits_placeholder": "Credits",
        "gpa_description": "Calculation of weighted GPA with credits",
        "gpa_fill_all": "Please check entered data. All fields must be filled correctly.",
        "gpa_formula": "GPA = Σ(grade points × credits) / Σ(credits)",
        "gpa_gpa_col": "GPA",
        "gpa_grade_col": "Grade (%)",
        "gpa_grade_placeholder": "Grade (%)",
        "gpa_insufficient": "Insufficient data for calculation. Add at least one subject with credits and grade.",
        "gpa_item_prefix": "Subject",
        "gpa_overall": "Overall GPA (weighted):",
        "gpa_subject_col": "Subject",
        "gpa_subject_name": "Subject name",
        "gpa_title": "📊 GPA Calculator",
        "gpa_warning": "⚠️ Important: Enter correct data for all subjects!",
        "gpa_weighted_col": "GPA × Credits",
        "grade_percentage": "Grade (%)",
        "grade_range": "Grade (0–100)",
        "high_comment_easy": " (difficult, but possible)",
        "high_comment_hard": " (almost impossible)",
        "high_impossible": "An increased scholarship is impossible with the current results.",
        "high_impossible_evil": "Increased scholarship? With these grades? Keep dreaming! 😂",
        "high_scholarship_title": "💎 Excellent! Increased scholarship!",
        "higher_scholarship": "Increased scholarship not possible",
        "important_info": "ℹ️ Important information:",
        "impossible_pass": "Impossible (need {value} > 100)",
        "impossible_scholarship": "Need more than 100 points. Maybe try a bribe? Just joking... or not 🤔",
        "impossible_scholarship_evil": "Need more than 100 points. Maybe try a bribe? Just joking... or not 🤔",
        "impossible_scholarship_serious": "Impossible to get a scholarship with current results.",
        "impossible_scholarship_standard": "Impossible to get a scholarship with current results.",
        "invalid_link": "❌ Link is invalid or expired",
        "invalid_msg_1": "Enter valid values from 0 to 100.",
        "invalid_msg_2": "Invalid data, check the grades range.",
        "kaspi_card": "Card number:",
        "kaspi_title": "🇰🇿 Kaspi transfer",
        "language_label": "Language",
        "link_copied": "✅ Link copied.",
        "main_description": "Select calculator type",
        "main_title": "GradeMaster - Main Page",
        "midterm": "Midterm",
        "minimum_points": "Minimum {value} points",
        "mode_evil": "Evil upperclassman",
        "mode_evil_msg": "Evil upperclassman mode.",
        "mode_serious": "Serious mode",
        "mode_serious_msg": "Serious analyst mode.",
        "mode_standard": "Standard mode",
        "mode_standard_msg": "Standard mode. All business.",
        "nav_evil": "Evil upperclassman",
        "nav_feedback": "💬 Feedback",
        "nav_home": "← Home",
        "nav_language": "🌐 Рус",
        "nav_mode": "Change mode",
        "nav_serious": "Serious mode",
        "nav_standard": "Standard mode",
        "nav_theme": "🌙 Theme",
        "option_att_desc": "Track and calculate attendance",
        "option_att_title": "📋 Attendance Calculator",
        "option_attendance_desc": "Convenient calculator for tracking attendance",
        "option_attendance_title": "📚 Attendance Calculator",
        "option_converter_desc": "Convert percentage grades to GPA",
        "option_converter_title": "🔄 Grade to GPA Converter",
        "option_cumulative_desc": "Calculate overall GPA with credits across multiple trimesters",
        "option_cumulative_title": "📈 Cumulative GPA",
        "option_feedback_desc": "Help improve the app",
        "option_feedback_title": "💬 Feedback",
        "option_gpa_desc": "Calculator to understand your grades",
        "option_gpa_title": "📊 GPA Calculator",
        "option_templates_desc": "Ready-made settings for popular specialties",
        "option_templates_title": "📚 Subject Templates",
        "option_total_desc": "Calculator to understand how hard you need to prepare",
        "option_total_title": "🚀 Final Grade Calculator",
        "page_title_attendance": "Attendance Calculator - GradeMaster",
        "page_title_cumulative": "Cumulative GPA — GradeMaster",
        "page_title_feedback": "GradeMaster - Feedback",
        "page_title_gpa": "GPA Calculator - GradeMaster",
        "page_title_template": "Grade Calculator - Structured",
        "page_title_total": "GradeMaster - Grade Calculator",
        "pass_msg_1": "You passed the course. Final grade is normal.",
        "pass_msg_2": "Course completed successfully, congratulations!",
        "pass_title": "⚠️ Retake",
        "percentage_label": "Final grade in percentage (%):",
        "percentage_placeholder": "Example: 85",
        "prediction_msg_1": "Forecast of required points on final exam.",
        "prediction_msg_2": "Let's see how many points you need on the final.",
        "prediction_title": "🔮 Forecast",
        "preset_description": "Save weights and the list of work in a link. Grades are not included.",
        "preset_error": "❌ Could not create a preset link.",
        "preset_invalid": "❌ The preset link is invalid or outdated.",
        "preset_link_label": "Preset link",
        "preset_loaded": "📥 Preset loaded from the link.",
        "preset_save": "Save preset",
        "preset_saved": "✅ Preset saved. You can share the link.",
        "preset_title": "🔗 Subject preset",
        "qr_description": "Scan QR code to open Kaspi app with filled details:",
        "quick_transfer": "📱 Quick transfer via Kaspi",
        "quiz": "Quiz",
        "quizzes": "Quizzes",
        "regend_below_25_evil": "RegEnd < 25... Seems like someone skipped important lectures. Or all of them.",
        "regend_below_25_serious": "RegEnd is below minimum threshold. Course cannot be completed.",
        "regend_below_25_standard": "RegEnd is less than 25. Retake is inevitable.",
        "regend_label": "RegEnd (0-100)",
        "regend_placeholder": "Enter grade",
        "regmid_below_25": "RegMid < 25? Seriously? Do you even attend classes? 💀",
        "regmid_below_25_standard": "RegMid is less than 25. Retake is inevitable.",
        "regmid_below_minimum": "RegMid is below minimum threshold. Course cannot be completed.",
        "regmid_label": "RegMid (0-100)",
        "regmid_placeholder": "Enter grade",
        "regterm_below_50": "RegTerm < 50. Congratulations, you did not even reach final and already have a retake!",
        "regterm_below_50_serious": "RegTerm is below minimum threshold. Course cannot be completed.",
        "regterm_below_50_standard": "RegTerm is less than 50. Retake is inevitable.",
        "regterm_calculated": " (calculated from RegMid and RegEnd)",
        "regterm_direct_input": " (entered directly)",
        "regterm_display": "RegTerm: {value}{source}",
        "regterm_label": "RegTerm (0-100)",
        "regterm_placeholder": "Or enter RegTerm directly",
        "regterm_source_calc": " (calculated from RegMid and RegEnd)",
        "remove_item": "Remove row",
        "retake_evil": "Final is between 25 and 50. Fate gave a second chance, do not mess up.",
        "retake_serious": "Exam not passed, but retake opportunity is provided.",
        "retake_standard": "Retake. You have a second chance.",
        "retake_title": "⚠️ Retake",
        "scholarship_title": "✅ Success! Regular scholarship!",
        "secret_auto_passing": "Auto-passing exam function is still in development...",
        "secret_calculator_scholarship": "If this calculator were a student, it would have a scholarship!",
        "secret_calculator_student": "Know why this calculator is so accurate? It never cheated on exams!",
        "secret_difference": "Know the difference between a student and this calculator? Calculator always calculates correctly!",
        "secret_easter_egg": "Congratulations egg hunter, maybe there's something on other pages too?)",
        "secret_excuse": "Congratulations! You found an excuse not to prepare for the exam!",
        "secret_extra_1": "Easter egg! You found a secret! 🥚",
        "secret_extra_10": "The developer was here 🐛",
        "secret_extra_11": "This message will self-destruct in 5... 4... 3... just kidding!",
        "secret_extra_12": "An Easter egg for the “I should be studying” achievement",
        "secret_extra_13": "Inside information: teachers use calculators too!",
        "secret_extra_14": "The secret ingredient for a good grade is confidence (and this calculator)",
        "secret_extra_15": "The “auto-skip classes” feature is temporarily disabled... unfortunately",
        "secret_extra_16": "What do this calculator and good grades have in common? Both need the right input!",
        "secret_extra_17": "Attention! Calculator use has been linked to lower panic levels!",
        "secret_extra_2": "The developer of this calculator sometimes fails exams too 😅",
        "secret_extra_3": "Did you know the first calculator was made in the 17th century?",
        "secret_extra_4": "This calculator was made with ♥ and lots of coffee ☕",
        "secret_extra_5": "Fun fact: 87% of students find Easter eggs while preparing for exams",
        "secret_extra_6": "Psst... between us, RegMid weighs 30%, but everyone pretends otherwise",
        "secret_extra_7": "Developer tip: an Easter egg a day keeps exam fears away!",
        "secret_extra_8": "Fact: 100% of this calculator’s users successfully get distracted from studying!",
        "secret_extra_9": "Secret formula: sleep + food + this calculator = successful exams!",
        "secret_hack": "Hacker advice: to pass the exam, you need to show up to it 😉",
        "secret_leak": "Warning! Leak detected: final is 40% of the grade!",
        "secret_manual_check": "Secret advice: always double-check calculations manually!",
        "secret_rare_user": "You are 1 in 1000 users who found this easter egg!",
        "secret_subtitle": "👀 Looking for hidden meaning? There is none!",
        "secret_success": "Secret to success: 10% luck, 20% skills, 70% this calculator!",
        "secret_theme": "🎨 An artist? You switch themes so quickly!",
        "secret_triple": "🎉 Triple click! Classes must be getting boring!",
        "secret_warning": "Warning: excessive use of the calculator may lead to... good grades!",
        "select_amount": "Select amount (₸):",
        "serious_impossible_high": "Impossible to get increased scholarship with current results.",
        "serious_pass_comment": "",
        "serious_scholarship_comment_easy": " (high difficulty)",
        "serious_scholarship_comment_hard": " (extremely difficult)",
        "serious_scholarship_comment_medium": " (very high difficulty)",
        "share_button": "🔗 Create link for a friend",
        "share_copied_success": "✅ Link copied to clipboard!",
        "share_created": "✅ Link created! It is valid for 24 hours.",
        "share_created_success": "✅ Link created! Data saved in link.",
        "share_data_loaded": "📥 Data loaded from shared link!",
        "share_info": "This link saves entered data to share with a friend",
        "share_link_label": "Share link:",
        "share_loaded": "📥 Data loaded from the shared link!",
        "sigma_credits": "Σ(credits)",
        "sigma_gpa_credits": "Σ(GPA × credits)",
        "standard_empty_1": "Fill in all fields for calculation.",
        "standard_empty_2": "Do not forget to enter all grades.",
        "standard_fail_1": "Unfortunately, the result is below passing score.",
        "standard_fail_2": "Retake is necessary, time to resit.",
        "standard_high_1": "Excellent result! You showed high level of knowledge.",
        "standard_high_2": "Excellent! Keep it up.",
        "standard_high_scholarship_1": "Excellent! You get an increased scholarship!",
        "standard_high_scholarship_2": "Highest result! Increased scholarship guaranteed!",
        "standard_high_scholarship_comment_easy": " (difficult, but achievable)",
        "standard_high_scholarship_comment_hard": " (almost impossible)",
        "standard_high_scholarship_comment_medium": " (very difficult)",
        "standard_invalid_1": "Grades must be from 0 to 100.",
        "standard_invalid_2": "Invalid value, check the range.",
        "standard_pass_1": "You passed the course. Final grade is normal.",
        "standard_pass_2": "Course completed successfully, congratulations!",
        "standard_pass_comment_easy": " (achievable)",
        "standard_pass_comment_hard": " (very difficult)",
        "standard_pass_comment_medium": " (good preparation needed)",
        "standard_scholarship_1": "Congratulations! You get a scholarship.",
        "standard_scholarship_2": "Scholarship is yours, well done!",
        "standard_scholarship_comment_easy": " (good chance)",
        "standard_scholarship_comment_hard": " (very high bar)",
        "standard_scholarship_comment_medium": " (serious preparation)",
        "subject": "Subject",
        "subject_name": "Subject name {number}",
        "subjects_count": "Number of subjects:",
        "success_high_scholarship": "💎 Excellent! Increased scholarship!",
        "success_scholarship": "✅ Success! Regular scholarship!",
        "support_button": "Support the author",
        "support_description": "❤️ GradeMaster is a free non-commercial project for students",
        "support_title": "🤝 Support the Project",
        "support_warning": "This is voluntary support for a non-commercial project. All calculators remain completely free.",
        "template_add_assignment": "+ Add Assignment",
        "template_add_exam": "+ Add Exam",
        "template_add_quiz": "+ Add Quiz",
        "template_assignments_title": "📝 Assignments",
        "template_calculate_btn": "Calculate final grade",
        "template_copy_preset_btn": "Copy",
        "template_current_weight_label": "Current total weight:",
        "template_exams_title": "📊 Midterm/Endterm",
        "template_excellent": "Excellent!",
        "template_excellent_comment": "Excellent result!",
        "template_good": "Good",
        "template_good_comment": "Course completed successfully!",
        "template_grade_placeholder": "Grade (0-100)",
        "template_overall_result": "Overall result:",
        "template_preset_copied": "✅ Link copied.",
        "template_preset_corrupted": "❌ Preset link is corrupted or expired.",
        "template_preset_create_error": "❌ Failed to create preset link.",
        "template_preset_description": "Save weights and assignments list to link. Grades are not included in preset.",
        "template_preset_header": "🔗 Subject Preset",
        "template_preset_loaded": "📥 Preset loaded from link.",
        "template_preset_saved": "✅ Preset saved. You can share the link with someone.",
        "template_quizzes_title": "📋 Quizzes",
        "template_satisfactory": "Satisfactory",
        "template_satisfactory_comment": "Course passed, but there is room to grow",
        "template_save_preset_btn": "Save preset",
        "template_sum_warning": "⚠️ Important: The sum of all section weights must equal 100%",
        "template_totals": "📈 Totals",
        "template_totals_header": "📈 Totals",
        "template_unsatisfactory": "Unsatisfactory",
        "template_unsatisfactory_comment": "Retake required",
        "template_weight_label": "Weight:",
        "term_credits_placeholder": "Credits",
        "term_gpa_placeholder": "Trimester GPA",
        "terms_count": "Number of trimesters:",
        "thank_you": "🙏 Thank you for your support!",
        "theme_label": "Theme",
        "total_details": "RegTerm: {regterm}{source} | Total: {total}",
        "warning_pass": "⚠️ No scholarship",
        "warning_text": "⚠️ Important: Cheating leads to expulsion!",
        "weight": "Weight:",
        "weight_current": "Current weight total:",
        "weight_warning": "⚠️ Section weights must add up to 100%.",
        "welcome": "Welcome to GradeMaster!",
        "yoomoney_title": "💰 YooMoney (Yandex.Money)",
        "yoomoney_wallet": "Wallet:"
}
};

if (typeof window !== 'undefined') {
    window.translations = translations;
}
