MENU = 0
LANG = 1
GPA_COUNT = 2
GPA_SUBJECT_NAME = 3
GPA_SUBJECT_CREDITS = 4
GPA_SUBJECT_GRADE = 5
ATT_LESSONS = 6
TOTAL_HAS_REGTERM = 7
TOTAL_REGTERM = 8
TOTAL_REGMID = 9
TOTAL_REGEND = 10
TOTAL_FINAL = 11
TEMPLATE_WEIGHTS = 12
TEMPLATE_ASSIGN_GRADES = 13
TEMPLATE_QUIZ_GRADES = 14
TEMPLATE_EXAM_GRADES = 15

